cache:
    directories:
        - node_modules
        - client/node_modules
dist: trusty
env: NODE_ENV=ci PORT=3000
install:
    - 'npm install'
language: node_js
node_js:
    - '8'
before_script:
    - npm run build
    - nohup npm run start &
script:
    - 'sleep 9'
    - 'npm run test'
services:
    - mongodb
    - redis-server
