cache:
    directories:
        - node_modules
        - client/node_modules
dist: trusty
env: NODE_ENV=ci PORT=3000
install:
    - 'npm install'
    - npm run build
language: node_js
node_js:
    - '8'
before_script:
    - nohup npm run start &
    - 'sleep 9'
script:
    - 'npm run test'
services:
    - mongodb
    - redis-server
